### ISSUE TITLE
Error on deploy

### ISSUE THREAD

**Issue by alykat** [nprapps/elections16graphics#1]
Getting an error when I try to publish to staging:

```
(elections16graphics)ahurt-npr-2:elections16graphics AHurt$ fab staging deploy:map-election-results-standalone
[cron-staging.nprapps.org] Executing task 'deploy'
Installing font
INFO:fabfile.utils:2016-10-12 12:25:54,362: Font installed, skipping.
INFO:fabfile.assets:2016-10-12 12:25:55,368: Ignoring: www/assets/assetsignore
[localhost] local: node_modules/less/bin/lessc less/app.less www/css/app.less.css
[localhost] local: node_modules/less/bin/lessc less/graphics-base.less www/css/graphics-base.less.css
[localhost] local: node_modules/less/bin/lessc less/map-election-results-standalone.less www/css/map-election-results-standalone.less.css
[localhost] local: node_modules/less/bin/lessc less/oauth.less www/css/oauth.less.css
[localhost] local: node_modules/universal-jst/bin/jst.js --template underscore jst www/js/templates.js
INFO:fabfile.render:2016-10-12 12:25:56,476: Skipping static._app_config_js
INFO:fabfile.render:2016-10-12 12:25:56,476: Skipping static._templates_js
INFO:fabfile.render:2016-10-12 12:25:56,476: Skipping static._copy_js
INFO:fabfile.render:2016-10-12 12:25:56,476: Skipping _oauth.authenticate
INFO:fabfile.render:2016-10-12 12:25:56,476: Skipping _oauth.oauth_alert
INFO:fabfile.render:2016-10-12 12:25:56,476: Skipping static
INFO:fabfile.render:2016-10-12 12:25:56,476: Skipping static._less
INFO:fabfile.render:2016-10-12 12:25:56,476: Rendering www/<slug>/child.html
Traceback (most recent call last):
  File "/Users/AHurt/.virtualenvs/elections16graphics/lib/python2.7/site-packages/fabric/main.py", line 756, in main
    *args, **kwargs
  File "/Users/AHurt/.virtualenvs/elections16graphics/lib/python2.7/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/Users/AHurt/.virtualenvs/elections16graphics/lib/python2.7/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/Users/AHurt/.virtualenvs/elections16graphics/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/AHurt/src/elections16graphics/fabfile/__init__.py", line 168, in deploy
    render.render_all()
  File "/Users/AHurt/.virtualenvs/elections16graphics/lib/python2.7/site-packages/fabric/tasks.py", line 171, in __call__
    return self.run(*args, **kwargs)
  File "/Users/AHurt/.virtualenvs/elections16graphics/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/AHurt/src/elections16graphics/fabfile/render.py", line 141, in render_all
    content = view().data
  File "/Users/AHurt/src/elections16graphics/oauth.py", line 71, in decorated_function
    return f(*args, **kwargs)
TypeError: child() takes exactly 1 argument (0 given)
```

**Comment by eads** [comment]
Sounds like the `<slug>` isn't getting subbed in properly.
